
%% ===================================================================== %%
% The code is (C) 2014-2015 Filipe I. Fazanaro, Diogo C. Soriano, Ricardo
% Suyama, Marconi K. Madrid, Jose Raimundo de Oliveira, Ignacio B. Munoz,
% Romis Attux and is released under the GPL v3 license.
%
% Sample code for the "Numerical Characterization of Nonlinear Dynamical
% Systems Using Parallel Computing: The Role of GPUs Approach" paper, which
% was submitted to the Communications of Nonlinear Science and Numerical
% Computation.
%
%
% Initial version: October 21, 2014
% Last update: June 15, 2020
%
%% ===================================================================== %%
%% DESCRIPTION
%
%   - Calculation of the Lyapunov global exponents - using the Clonded
%   Dynamics approach - for the Chua's circuit oscillator dynamical model 
%   [3,4].
%
%   - Defines 'alpha' as the control parameter.
%
%   - Employs the 'ode45' integrator.
%
%   - Uses the parfor function. See MATLAB documentation for further
%   details.
%
%
%% ===================================================================== %%
%% OBSERVATIONS
%
%   - Core i7 2600K 3.4GHz, MATLAB R2020a
%       - alpha variation step: 0.01
%       - Total execution time [s] = 261.8096
%
%
%% ===================================================================== %%
%% REFERENCES
%
% [1] Parker and Chua (1989) Practical Numerical algorithms for Chaotic
% Systems. Springer-Verlag.
%
% [2] Soriano, Fazanaro, Suyama, JRO, Attux and Madrid (2012) A method for
% Lyapunov spectrum estimation using cloned dynamics and its application
% to the discontinuously-excited FitzHugh-Nagumo model. Nonlinear Dynamics,
% vol 67, no 1, pp 413-424.
% DOI: 10.1007/s11071-011-9989-2.
%
% [3] Matsumoto, Chua, Komuro (1985) The Double Scroll. IEEE Transactions
% on Circuits and Systems CAS-32(8), pp 798-818.
%
% [4] Arena, Baglio, Fortuna, Manganaro (1995) Chua's Circuit Can be
% Generated by CNN Cells. IEEE Transactions on circuits ans Systems - I:
% fundamental, Theory and Applications, vol 42, no 2, February, pp 123-125.
%% ===================================================================== %%

clc
close all
clear all


%% ===================================================================== %%
%% DEFINES THE PROCESSORS/THREADS POOL SIZE

PoolSize = 4;

%% ===================================================================== %%
%% DYNAMICAL SYSTEM DIMENSION

dim = 3;

dim_total = dim*(dim+1);

%% ===================================================================== %%
%% PARAMETERS
%
%   - See [3] for aditional details

% -------------------------------------------------------------------------
% C1 = 1/7;
% C2 = 1/1;
% L  = 1/7;
% RL = 0;
% G  = 0.7;
% m0 = -0.5;
% m1 = -0.8;
% Bp = 1;
% 
% alpha = C2/C1;
% beta  = C2/(L*G^2);
% gamma = (RL*C2)/(G*L);
% 
% a = m1/G;
% b = m0/G;
% -------------------------------------------------------------------------

% -------------------------------------------------------------------------
%alpha = 9;
beta  = 100/7;
gamma = 0;

a = -8/7;
b = -5/7;
% -------------------------------------------------------------------------

%% ===================================================================== %%
%% CONTROL PARAMETERS

% Variation step of the control parameter
nIncControlParameter = 0.01;

% Control parameter
vAlpha = 7.0:nIncControlParameter:9.0;

%% ===================================================================== %%
%% INTEGRATION PARAMETERS

% Initial time
t_init = 0;


% Final time
t_final = 1000;


% Time step
t_step = 0.01;


% Gram-Schimidt reorthonormalization time interval
%   - See [2] for further details related to how to change this value.
t_gsr = 0.5;


% Maximum iteration number
nMaxItera = round( (t_final-t_init)/t_gsr );


% Store the Lyapunov spectrum
vBifurcLyap = 255*ones( length(vAlpha), (dim+1) );


% 'ode45' options
Options = odeset('RelTol',1e-8,'AbsTol',1e-8);

%% ===================================================================== %%
%% PARFOR INITIALIZATION

% When using MATLAB R2012b ...
%matlabpool( 'open', 'local', PoolSize );

% When using MATLAB R2014a ...
poolobj = parpool( PoolSize );

%% ===================================================================== %%

fprintf ( 1, '\n  Computation begun at %s.\n\n', datestr ( now ) );

tbase = tic();

%% ===================================================================== %%


parfor_progress( numel(vAlpha) );


%% ===================================================================== %%
%% DYNAMICAL SYSTEM INTEGRATION

parfor iAlpha = 1:length(vAlpha)
    
    % ------------------------------------------------------------------- %
    
    alpha = vAlpha(iAlpha);
    
    % ------------------------------------------------------------------- %
    
    t_aux = 0;
    
    % ------------------------------------------------------------------- %
    % INITIAL CONDITIONS OF THE DYNAMICAL AND THE CLONED SYSTEMS
    % ------------------------------------------------------------------- %
    
    % Cloned dynamical systems perturbation - see [5]
    delta = 1e-4;
    
    % Initial conditions
    vX0 = 0.15264;
    vY0 = -0.02281;
    vZ0 = 0.38127;
    
    y_init_orig  = [ vX0, vY0, vZ0 ];
    
    
    % Cloned dynamical systems initial conditions
    y_init_clon = (ones(dim,1)*y_init_orig)' + delta*eye(dim);
    
    % Fiducial and clones initial conditions
    y_init = [ y_init_orig, reshape(y_init_clon',1,[])];
    
    
    % ------------------------------------------------------------------- %
    % CLONED DYNAMICS APPROACH AUX
    % ------------------------------------------------------------------- %
    
    deltax = zeros( dim );
    
    % ------------------------------------------------------------------- %
    % MEMORY ALLOCATION
    % ------------------------------------------------------------------- %
    
    LyapSoma  = zeros( dim, nMaxItera );
    LyapLocal = zeros( dim, nMaxItera );
    Lyap      = zeros( dim, nMaxItera );
    
    % ------------------------------------------------------------------- %
    
    for ii = 1:nMaxItera
        
        % --------------------------------------------------------------- %
        
        [T,Y] = ode45(@(t,y) ChuaAdim1985_ClDyn( t, y, alpha, beta, gamma, a, b ), (t_aux:t_step:(t_aux+t_gsr)), y_init, Options);
        
        % --------------------------------------------------------------- %
        
        t_aux = t_aux + t_gsr;
        
        % --------------------------------------------------------------- %
        % You only need the conditions at the end of the 't_gsr' interval
        
        y_orig = Y( end, 1:dim )';
        y_clon = Y( end, (dim+1):(dim*(dim+1)));
        
        y_clon = reshape( y_clon, dim, [] )';
        
        % --------------------------------------------------------------- %
        % Difference state vectors
        
        deltax = y_orig*ones( 1, dim ) - y_clon;
        
        % --------------------------------------------------------------- %
        % Gram-Schimidt Reorthonormalization
        
        [vk, uk, Normk] = GSR2(deltax, dim);
        
        % --------------------------------------------------------------- %
        % Lyapunov exponents calculation
        
        for jj = 1:dim
            if norm(vk(:,jj)) ~= 0
                % Local exponent
                LyapLocal(jj,ii+1) = (1/t_gsr)*log(norm(vk(:,jj))/delta);
                
                % Local exponents summation
                LyapSoma(jj,ii+1) = LyapSoma(jj,ii) + log(norm(vk(:,jj))/delta);
                
                % Global Lyapunov exponents
                Lyap(jj,ii+1) = (1/(t_aux-t_init))*LyapSoma(jj,ii+1);
            end
        end
        
        % --------------------------------------------------------------- %
        % PREPARE FOR THE NEXT ITERATION
        % --------------------------------------------------------------- %
        
        % Fiducial and cloned dynamical systems initial conditions for the
        % next iteration
        
        y_init_orig = y_orig';
        y_init_clon = (ones(dim,1)*y_init_orig)' + delta*uk;
        
        y_init = [ y_init_orig, reshape(y_init_clon',1,[]) ];
        
        % --------------------------------------------------------------- %
        
    end
    
    % ------------------------------------------------------------------- %
    
    vBifurcLyap(iAlpha,:) = [ alpha, Lyap(:,end)' ];
    
    % ------------------------------------------------------------------- %
    
    parfor_progress;
    
    % ------------------------------------------------------------------- %
    
end

%% ===================================================================== %%


parfor_progress(0);


%% ===================================================================== %%

fprintf ( 1, '\n  Computation completed at %s.\n', datestr ( now ) );

cpuTime = toc( tbase );

fprintf('Total execution time [s] = %.4f\n\n',cpuTime);

%% ===================================================================== %%

% Uncomment if you are using MATLAB R2012b
%matlabpool('close');

% Uncomment if you are using MATLAB R2014a
delete(poolobj);

%% ===================================================================== %%
%% SOME USEFULL STRINGS

% Uncomment as you wish

% stralpha = ['alpha_' num2str( alpha ) ];
% stralpha( ismember(stralpha, '-') ) = 'n';
% stralpha( ismember(stralpha, '.') ) = 'p';
%
%
% strGamma = ['Gamma_' num2str( gamma ) ];
% strGamma( ismember(strGamma, '-') ) = 'n';
% strGamma( ismember(strGamma, '.') ) = 'p';
%
%
% strOmega = ['Omega_' num2str( omega ) ];
% strOmega( ismember(strOmega, '-') ) = 'n';
% strOmega( ismember(strOmega, '.') ) = 'p';

%% ===================================================================== %%
%% SAVE THE DATA

% Uncomment as you wish

% sSave = ['save <put_the_name_of_the_file_here>.mat'];
% evAlphal(sSave);

%% ===================================================================== %%
%% PLOT

close all

% ----------------------------------------------------------------------- %

set(0,'DefaultTextFontName','Times', ...
    'DefaultTextFontSize', 18, ...
    'DefaultAxesFontName', 'Times', ...
    'DefaultAxesFontSize', 18, ...
    'DefaultLineLineWidth', 1, ...
    'DefaultLineMarkerSize', 7.75);

% ----------------------------------------------------------------------- %
% http://dgleich.wordpress.com/2013/06/04/creating-high-quality-graphics-in-matlab-for-papers-and-presentations/
%
% Defaults for this blog post

width = 3;                  % Width in inches

height = 3;                 % Height in inches

AxesLineWidth = 0.75;       % AxesLineWidth

FontSize = 18;              % Fontsize

LFontSize = 18;             % Legend Fontsize

AnnotationFontSize = 20;    % Annotation Fontsize

LineWidth = 1;              % LineWidth

MarkerSize = 2;             % MarkerSize

% ----------------------------------------------------------------------- %

figure(1)

% plot(vBifurcLyap(:,1),0.0,...
%     'Marker', '.', ...
%     'LineStyle','-', ...
%     'Color',[0 0 0]);

line([min(vAlpha) max(vAlpha)], [0 0], ...
    'Color', [0 0 0]);

hold on;

plot(vBifurcLyap(:,1),vBifurcLyap(:,2:end),...
    'Marker','.', 'MarkerSize',2, ...
    'LineStyle','-');

hold on;


% axis([ min(vGamma) max(vGamma) -0.6 0.3 ]);


xlabel( '$\alpha$', 'Interpreter', 'latex' );
ylabel( '$\lambda$', 'Interpreter', 'latex' );


% Create textbox
annotation(figure(1),'textbox',...
    [0.318324185248713 0.814645308924485 0.057319039451115 0.068649885583524],...
    'Color',[0 0.447058823529412 0.741176470588235],...
    'String',{'\lambda_1'},...
    'LineStyle','none',...
    'FontSize',14,...
    'FontName','Fira Sans',...
    'FitBoxToText','off');


% Create textbox
annotation(figure(1),'textbox',...
    [0.318324185248713 0.606407322654462 0.0573190394511151 0.068649885583524],...
    'Color',[0.850980392156863 0.325490196078431 0.0980392156862745],...
    'String','\lambda_2',...
    'LineStyle','none',...
    'FontSize',14,...
    'FontName','Fira Sans',...
    'FitBoxToText','off');


% Create textbox
annotation(figure(1),'textbox',...
    [0.318324185248713 0.508009153318078 0.0573190394511151 0.0686498855835239],...
    'Color',[0.929411764705882 0.694117647058824 0.125490196078431],...
    'String','\lambda_3',...
    'LineStyle','none',...
    'FontSize',14,...
    'FontName','Fira Sans',...
    'FitBoxToText','off');


% ----------------------------------------------------------------------- %

figure(2)

% plot(vBifurcLyap(:,1),0.0,...
%     'Marker', '.', ...
%     'LineStyle','-', ...
%     'Color',[0 0 0]);

line([min(vAlpha) max(vAlpha)], [0 0], ...
    'Color', [0 0 0]);

hold on;

plot(vBifurcLyap(:,1),vBifurcLyap(:,2),...
    'Marker','.', ...
    'LineStyle','-');

hold on;


% axis([ min(vGamma) max(vGamma) -0.6 0.3 ]);


xlabel( '$\alpha$', 'Interpreter', 'latex' );
ylabel( '$\lambda_1$', 'Interpreter', 'latex' );

% ----------------------------------------------------------------------- %

% Print the figure
% sGraficoEPS = ['print -depsc2 fig_Duffing1989_bifurc_Lyap_vAlpha_' num2str(vAlpha(1)) 'a' num2str(vAlpha(end)) '.eps'];
% evAlphal(sGraficoEPS);
% ======================================================================= %



%% ===================================================================== %%
%% EOF: End Of File
%% ===================================================================== %%